import { AlertTriangle, Archive, Brain, FileText, Inbox, Megaphone, PenLine, Settings, ShieldCheck, Trash2 } from "lucide-react";
import type { Mailbox } from "../types";
type Props = { mailboxes: Mailbox[]; activeFolder: string; advertisingActive: boolean; advertisingCount: number; phishingEnabled: boolean; onCompose: () => void; onFolder: (folder: string) => void; onAdvertising: () => void; onSettings: () => void };
const special = (box: Mailbox) => box.flags.map((value) => value.toLowerCase());
function FolderIcon({ box }: { box: Mailbox }) { const flags = special(box); if (flags.includes("\\drafts")) return <FileText />; if (flags.includes("\\sent")) return <Archive />; if (flags.includes("\\trash")) return <Trash2 />; return <Inbox />; }
function displayName(box: Mailbox) { const flags = special(box); if (flags.includes("\\drafts")) return "Concepten"; if (flags.includes("\\sent")) return "Verzonden"; if (flags.includes("\\trash")) return "Prullenbak"; if (flags.includes("\\junk")) return "Ongewenst"; if (flags.includes("\\archive")) return "Archief"; return box.name.replace(/^INBOX[./]/i, ""); }
export function Sidebar({ mailboxes, activeFolder, advertisingActive, advertisingCount, phishingEnabled, onCompose, onFolder, onAdvertising, onSettings }: Props) {
  const inbox = mailboxes.find((box) => special(box).includes("\\inbox")) ?? mailboxes[0]; const secondary = mailboxes.filter((box) => box !== inbox);
  return <nav className="sidebar" aria-label="Mailnavigatie"><div className="brand"><span className="brand-mark">N</span><span>Nexin Mail</span></div><div className="account">Eén lokale mailbox <span>⌄</span></div><button className="compose-button" onClick={onCompose}><PenLine /><span>Nieuw bericht</span></button>
    {inbox ? <button className={`nav-row ${!advertisingActive && activeFolder === inbox.name ? "active" : ""}`} onClick={() => onFolder(inbox.name)}><FolderIcon box={inbox} /><span>Postvak IN</span><strong>{inbox.unseen ?? 0}</strong></button> : null}
    <button className="nav-row"><Brain /><span>Prioriteit</span><strong>—</strong></button><button className={`nav-row ${advertisingActive ? "active" : ""}`} onClick={onAdvertising}><Megaphone /><span>Reclame</span><strong>{advertisingCount}</strong></button><button className="nav-row"><AlertTriangle /><span>Verdacht</span><strong className="danger-count">—</strong></button><div className="nav-separator" />
    {secondary.map((box) => <button key={box.folder_id} className={`nav-row ${!advertisingActive && activeFolder === box.name ? "active" : ""}`} onClick={() => onFolder(box.name)}><FolderIcon box={box} /><span>{displayName(box)}</span><strong>{box.messages ?? 0}</strong></button>)}<div className="sidebar-spacer" /><button className="nav-row" onClick={onSettings}><Settings /><span>Instellingen</span></button><div className={`shield-status ${phishingEnabled ? "enabled" : ""}`}><ShieldCheck /><span>Phishingschild {phishingEnabled ? "aan" : "uit"}</span></div></nav>;
}
