from __future__ import annotations

import json
import re
import urllib.parse
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOCKS = (ROOT / "requirements-runtime.lock", ROOT / "requirements-dev.lock")
PIN_RE = re.compile(
    r"^(?P<name>[A-Za-z0-9_.-]+)==(?P<version>[^\s;]+)(?P<marker>\s*;\s*.+)?$"
)


def _normalized_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def _pins(path: Path) -> list[tuple[str, str, str]]:
    pins: list[tuple[str, str, str]] = []
    current = ""
    for raw in path.read_text(encoding="utf-8").splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        current = f"{current} {stripped}".strip()
        if current.endswith("\\"):
            current = current[:-1].rstrip()
            continue
        requirement = re.split(r"\s+--hash=", current, maxsplit=1)[0].strip()
        match = PIN_RE.fullmatch(requirement)
        if match is None:
            raise RuntimeError(f"unsupported dependency pin in {path.name}: {requirement}")
        pins.append((match["name"], match["version"], match["marker"] or ""))
        current = ""
    if current:
        raise RuntimeError(f"unterminated requirement continuation in {path.name}")
    return pins


def _release_hashes(name: str, version: str) -> list[str]:
    package = urllib.parse.quote(name, safe="")
    release = urllib.parse.quote(version, safe="")
    request = urllib.request.Request(
        f"https://pypi.org/pypi/{package}/{release}/json",
        headers={"User-Agent": "imap-plugin-dependency-lock/1"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.load(response)
    if str(payload.get("info", {}).get("version", "")) != version:
        raise RuntimeError(f"PyPI returned an unexpected version for {name}=={version}")
    published_name = str(payload.get("info", {}).get("name", ""))
    if _normalized_name(published_name) != _normalized_name(name):
        raise RuntimeError(f"PyPI returned an unexpected project for {name}=={version}")
    hashes = sorted(
        {
            str(item.get("digests", {}).get("sha256", "")).lower()
            for item in payload.get("urls", [])
            if item.get("packagetype") == "bdist_wheel"
            and not item.get("yanked", False)
            and item.get("digests", {}).get("sha256")
        }
    )
    if not hashes or any(not re.fullmatch(r"[0-9a-f]{64}", value) for value in hashes):
        raise RuntimeError(f"PyPI returned no valid SHA-256 artifacts for {name}=={version}")
    return hashes


def _render(path: Path) -> str:
    output = ["# Generated by scripts/refresh_dependency_hashes.py; review every update before commit."]
    for name, version, marker in _pins(path):
        hashes = _release_hashes(name, version)
        output.append(f"{name}=={version}{marker} \\")
        for index, digest in enumerate(hashes):
            suffix = " \\" if index < len(hashes) - 1 else ""
            output.append(f"    --hash=sha256:{digest}{suffix}")
    return "\n".join(output) + "\n"


def main() -> None:
    rendered = {path: _render(path) for path in LOCKS}
    for path, content in rendered.items():
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"updated {path.name}")


if __name__ == "__main__":
    main()
